version: "3"
services:
  spring-net:
    image: spring-net
    restart: always
    build: .
    ports:
      - 8090:8080
    environment:
       MYSQL_HOST: mysqlamk
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_PORT: 3306
       
  mysqlamk:
    container_name: mysqlamk
    image: mysql:5.6
    ports:
      - 3307:3306
    environment:
        MYSQL_DATABASE: ammu
        MYSQL_ROOT_PASSWORD: root
    